project:
  name: cloudformation-cicd
  regions:
    - ap-northeast-1
  s3_bucket: cloudformation-cicd-codebuild-bucket
tests:
  ec2-test:
    parameters:
      SubnetCidr: 10.0.125.0/24
      Ec2SgName: ec2-sg-cf-taskcat
    template: ./sam-templated.yaml