AWSTemplateFormatVersion: 2010-09-09
Resources:
  CODECOMMIT:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: CloudFormationTemplate
      RepositoryDescription: cloudformation templates with cicd
    Tags:
        - Key: Project
          Value: Cfn-CICD