AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance with encrypted EBS volume for AWS CloudFormation Guard Testing"
Parameters:
  SubnetId:
    Description: SubnetId
    Type: AWS::EC2::Subnet::Id
    Default: TARGETSUBNETID
  ImageId:
    Description: Latest Amazon Linux 2 AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: 't3.micro'
      SubnetId: !Ref SubnetId
      BlockDeviceMappings:
      - DeviceName: /dev/sdf
        Ebs:
          VolumeSize: TARGETVOLUMESIZE
          VolumeType: gp2
      Tags:
      - Key: Name
        Value: cfn-cicd-ec2
    DeletionPolicy: Delete

Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref EC2Instance